server:
  port: 8083
  compression:
    enabled: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: log
#  level:
#    org.springframework.boot.autoconfigure: ERROR

spring:
  application:
    name: dubbo-order-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: order
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://192.168.1.7:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&'
    username: 'root'
    password: '123456'
    # 使用hikari数据源
    type: 'com.zaxxer.hikari.HikariDataSource'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: 'DatebookHikariCP'
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: 'SELECT 1'

dubbo:
  server: true
  application:
    name: dubbo-order-server
    qosEnable: false
  registry:
    id: dubbo-order-server
    protocol: zookeeper
    address: 192.168.1.7:2181
  protocol:
    name: dubbo
    port: 20883
  monitor:
    protocol: registry
  scan:
    basePackages: com.aaron.learn.dubbo.order.server.service

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
#  typeAliasesPackage: com.ytt.springcoredemo.model
  type-handlers-package: com.aaron.learn.dubbo.order.server.dao.mapper.handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    useGeneratedKeys: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

swagger:
  host: local.dev.com



